title: Brandon Biro
logo: /assets/BBiroPhoto.png
description: > |
  # Brandon Biro

  ![Brandon Biro headshot](assets/images/BBiroPhoto.png)

  I am a graduate student pursuing a Master of Science in Applied Business Analytics, with a passion for leveraging data to drive actionable insights and informed decision-making.

  With over a decade of professional experience in education and entrepreneurship, I am driven by curiosity and a desire to solve complex problems.

show_downloads: false
show_footer: false
theme: jekyll-theme-minimal
