title: Brandon Biro
logo: /assets/BBiroPhoto.png
description: >
  I am a graduate student pursuing a Master of Science in Applied Business Analytics.  
show_downloads: true
show_footer: true
theme: jekyll-theme-minimal
